browser=chrome
url=https://o2.openmrs.org/openmrs/login.htm
usernameValid=admin
passwordValid=Admin123

usernameInvalid=admi
passwordInvalid=Admin12

givenName=Samantha
familyName=Miller

givenNameInvalid=Sibel
givenNameForDelete=Satish
deleteReason=recovered
givenNameForAppointment=Dahlia